/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package awtproject;

import java.awt.Color;

/**
 *
 * @author ansab
 */
public class applet extends java.applet.Applet {

    /**
     * Initializes the applet applet
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        textField1 = new java.awt.TextField();
        button3 = new java.awt.Button();
        label1 = new java.awt.Label();
        scrollbar1 = new java.awt.Scrollbar();
        scrollbar2 = new java.awt.Scrollbar();
        scrollbar3 = new java.awt.Scrollbar();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();

        setBackground(new java.awt.Color(102, 102, 102));
        setName("G"); // NOI18N
        setLayout(null);

        button1.setBackground(new java.awt.Color(49, 200, 49));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(102, 102, 102));
        button1.setLabel("Change B-G color");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(30, 170, 200, 40);

        button2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        button2.setLabel("Change B-G of Btn 1");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(250, 170, 200, 40);

        textField1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        add(textField1);
        textField1.setBounds(30, 30, 160, 30);

        button3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        button3.setLabel("Submit");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(170, 90, 120, 40);

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        add(label1);
        label1.setBounds(280, 30, 160, 30);

        scrollbar1.setMaximum(255);
        scrollbar1.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        scrollbar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrollBarColor(evt);
            }
        });
        add(scrollbar1);
        scrollbar1.setBounds(30, 250, 420, 16);

        scrollbar2.setMaximum(255);
        scrollbar2.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        scrollbar2.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrollBarColor(evt);
            }
        });
        add(scrollbar2);
        scrollbar2.setBounds(30, 300, 420, 16);

        scrollbar3.setMaximum(255);
        scrollbar3.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        scrollbar3.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrollBarColor(evt);
            }
        });
        add(scrollbar3);
        scrollbar3.setBounds(30, 350, 420, 16);

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        label2.setText("Red");
        add(label2);
        label2.setBounds(30, 220, 170, 20);

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        label3.setText("Green");
        add(label3);
        label3.setBounds(30, 270, 170, 20);

        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        label4.setText("Blue");
        add(label4);
        label4.setBounds(30, 320, 170, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        this.setBackground(Color.BLACK);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        button2.setBackground(button1.getForeground());
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        label1.setText(textField1.getText());
    }//GEN-LAST:event_button3ActionPerformed

    private void scrollBarColor(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrollBarColor
        int i = scrollbar1.getValue();
        int j = scrollbar2.getValue();
        int k = scrollbar3.getValue();
        
        Color c = new Color(i, j, k);
        
        this.setBackground(c);
        
        label2.setText("Red "+ i);
        label3.setText("Green "+ j);
        label4.setText("Blue "+ k);
    }//GEN-LAST:event_scrollBarColor


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.Scrollbar scrollbar2;
    private java.awt.Scrollbar scrollbar3;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
